# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: 
          name: testing
          command: |
            TESTS=$(mktemp _test.txt.XXXXXX)
            echo "export TEST=$TESTS" >> $BASH_ENV
      - run: cp test.txt $TEST
workflows:
  welcome:
    jobs:
      - test

